CREATE DATABASE Checkpoint05CrudDB;
GO

USE Checkpoint05CrudDB;
GO

CREATE TABLE Produtos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    Estoque INT NOT NULL,
    Categoria NVARCHAR(100) NOT NULL
);
GO